services:
  db-snippet-manager:
    image: postgres:alpine
    container_name: db-snippets-manager-dev
    restart: always
    environment:
      - POSTGRES_DB=snippet-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_PORT=5433
      - DB_HOST=localhost
    ports:
      - '5433:5432'
    expose:
      - '5433'
    volumes:
      - db-data:/var/lib/postgresql/snippet-manager
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 1s
      timeout: 1s
      retries: 15
  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"
volumes:
  db-data: